Wayfinding blog
canada-ca/blogue-canada-ca-blog pull request #108
Opened 2022-11-30 18:55 UTC by prycrane

2022-12-07 18:42 UTC, delisma requested changes

2022-12-08 14:15 UTC, prycrane commented on _includes/footers/footer.html
> +<footer id="wb-info">
I'm not sure how to do this.  You'll have to show me.

2022-12-08 14:16 UTC, prycrane commented on _layouts/post-01.html
> +---
Same as above.

2022-12-08 14:19 UTC, prycrane commented on en/_posts/2022-11-29-wayfinding-project-improves-navigation.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
Not necessarily.  We can have this update for future blogs and keep the past blogs in its old look.  Greed that we should still do this at the template level.

2022-12-08 14:20 UTC, prycrane commented on en/_posts/2022-11-29-wayfinding-project-improves-navigation.md
> +layout: post-01
We can discuss.  Not sure what you mean here.

2022-12-08 14:20 UTC, prycrane commented on en/_posts/2022-11-29-wayfinding-project-improves-navigation.md
> +dateModified: 2022-11-29
Not sure what you mean here.

2022-12-08 14:21 UTC, prycrane commented on en/_posts/2022-11-29-wayfinding-project-improves-navigation.md
> +description: "The wayfinding study investigated issues with Canada.ca navigation and informed changes to improve navigation and simplify the adoption of the Canada.ca design for departments and agenc
Agreed.  I fixed this.

2022-12-08 14:21 UTC, prycrane commented on en/_posts/2022-11-29-wayfinding-project-improves-navigation.md
> +</div>
Agree with the templating.  For new blogs only.  Perhaps?

2022-12-08 14:23 UTC, prycrane commented on en/_posts/2022-11-29-wayfinding-project-improves-navigation.md
> +<div class="clearfix"></div>
Yeah.  Fixed.  No harm, no foul.  It's a bad habit I picked up.  :)

2022-12-09 12:40 UTC, closed without merging