RS Link update
canada-ca/blogue-canada-ca-blog pull request #145
Opened 2024-02-01 12:22 UTC by prycrane

2024-02-06 15:25 UTC, delisma requested changes

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +																<a href="https://conception.canada.ca/resumes-recherche/rappels-securite-resume-recherche.html">Résumé de recherche : Recherche de rappels et d'avis de sécurité</a>
```suggestion
																<a href="https://conception.canada.ca/resumes-recherche/rappels-securite-resume-recherche.html">Résumé de recherche&nbsp;: Recherche de rappels et d'avis de sécurité</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/conseils-voyageurs-resume-recherche.html">Résumé de recherche : Conseils aux voyageurs et avertissements</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/conseils-voyageurs-resume-recherche.html">Résumé de recherche&nbsp;: Conseils aux voyageurs et avertissements</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/arc-contactez-nous-resume-recherche.html">Résumé de recherche : Communiquer avec l'ARC</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/arc-contactez-nous-resume-recherche.html">Résumé de recherche&nbsp;: Communiquer avec l'ARC</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/maternite-parentales-resume-recherche.html">Résumé de recherche : Prestations de maternité et parentales d'assurance-emploi</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/maternite-parentales-resume-recherche.html">Résumé de recherche&nbsp;: Prestations de maternité et parentales d'assurance-emploi</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/prets-etudiants-resume-recherche.html">Résumé de recherche : Prêts et des bourses pour les étudiants</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/prets-etudiants-resume-recherche.html">Résumé de recherche&nbsp;: Prêts et des bourses pour les étudiants</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/trouver-emploi-resume-recherche.html">Résumé de recherche : Trouver un emploi »</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/trouver-emploi-resume-recherche.html">Résumé de recherche&nbsp;: Trouver un emploi »</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/examen-citoyennete-resume-recherche.html">Résumé de recherche : Se préparer à passer l'examen de citoyenneté</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/examen-citoyennete-resume-recherche.html">Résumé de recherche&nbsp;: Se préparer à passer l'examen de citoyenneté</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/comptes-entreprises-resume-recherche.html">Résumé de recherche : Gestion des comptes d'entreprise</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/comptes-entreprises-resume-recherche.html">Résumé de recherche&nbsp;: Gestion des comptes d'entreprise</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/rappels-resume-recherche.html">Résumé de recherche : Rappels et alertes de sécurité</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/rappels-resume-recherche.html">Résumé de recherche&nbsp;: Rappels et alertes de sécurité</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="..//resumes-recherche/prochesaidants-resume-recherche.html">Résumé de recherche : Prestations spéciales d'assurance-emploi</a>
```suggestion
															<a href="..//resumes-recherche/prochesaidants-resume-recherche.html">Résumé de recherche&nbsp;: Prestations spéciales d'assurance-emploi</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/impots-resume-recherche.html">Résumé de recherche : TPS/TVH et retenues sur la paie</a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/impots-resume-recherche.html">Résumé de recherche&nbsp;: TPS/TVH et retenues sur la paie</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
>  																<span class="wb-inv">Renseignements sur les maladies et la vaccination&nbsp;: </span>Résumé de recherche : Renseignements sur les maladies et la vaccination</a>
```suggestion
																<span class="wb-inv">Renseignements sur les maladies et la vaccination&nbsp;: </span>Résumé de recherche&nbsp;: Renseignements sur les maladies et la vaccination</a>
```

2024-02-06 15:25 UTC, delisma commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/meteo-resume-recherche.html">Résumé de recherche : Renseignements météorologiques </a>
```suggestion
															<a href="https://conception.canada.ca/resumes-recherche/meteo-resume-recherche.html">Résumé de recherche&nbsp;: Renseignements météorologiques </a>
```

2024-02-06 17:10 UTC, prycrane commented on fr/pages/apercu-projet.html
> +															<a href="..//resumes-recherche/prochesaidants-resume-recherche.html">Résumé de recherche : Prestations spéciales d'assurance-emploi</a>
fixed

2024-02-15 15:16 UTC, prycrane commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/prets-etudiants-resume-recherche.html">Résumé de recherche : Prêts et des bourses pour les étudiants</a>
done

2024-02-15 15:17 UTC, prycrane commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/trouver-emploi-resume-recherche.html">Résumé de recherche : Trouver un emploi »</a>
Done

2024-02-15 15:17 UTC, prycrane commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/examen-citoyennete-resume-recherche.html">Résumé de recherche : Se préparer à passer l'examen de citoyenneté</a>
Done

2024-02-15 15:17 UTC, prycrane commented on fr/pages/apercu-projet.html
> +															<a href="https://conception.canada.ca/resumes-recherche/comptes-entreprises-resume-recherche.html">Résumé de recherche : Gestion des comptes d'entreprise</a>
Done

2024-02-15 15:35 UTC, delisma approved these changes
LGTM 🚀

2024-02-15 15:37 UTC, merged