Unified ds post
canada-ca/blogue-canada-ca-blog pull request #162
Opened 2024-06-05 15:35 UTC by jmealing

2024-06-05 16:07 UTC, jmealing commented
@delisma Do you know why preview doesn't seem to show my post? Did I do something wrong?

2024-06-06 15:38 UTC, delisma commented
Can you change the title of the PR to Create `2024-06-06-unified-design-system posts`? Makes it easier to scan, when we look through the PR history.

2024-06-06 15:46 UTC, delisma requested changes

2024-06-06 15:46 UTC, delisma commented on en/_posts/2024-06-05-unified-design-system.md
> +<div class="clearfix">
```suggestion
```

2024-06-06 15:46 UTC, delisma commented on en/_posts/2024-06-05-unified-design-system.md
> +<div class="clearfix">
Clearfix are no longer necessary since the grid system doesn't rely on floats as much.

2024-06-06 15:46 UTC, delisma commented on en/_posts/2024-06-05-unified-design-system.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
```suggestion
```
There isn't any icons used on this page. Might be unnecessary.

2024-06-06 15:46 UTC, delisma commented on fr/_posts/2024-06-05-systeme-design-unifie.md
> +<div class="clearfix">
```suggestion
<div class="clearfix">
```
Clearfix are no longer necessary since the grid system doesn't rely on floats as much.

2024-06-06 15:46 UTC, delisma commented on fr/_posts/2024-06-05-systeme-design-unifie.md
> +- https://use.fontawesome.com/releases/v5.15.4/css/all.css
```suggestion
```
There isn't any icons used on this page. Might be unnecessary.

2024-06-06 15:59 UTC, jmealing commented
@delisma changes made as requested, ready to merge now?

2024-06-06 17:18 UTC, delisma commented
> @delisma changes made as requested, ready to merge now?

One last question. Do you want the publish date to be today or yesterday is fine?

2024-06-06 17:35 UTC, jmealing commented
@delisma I think it's fine to be yesterday

2024-06-06 17:39 UTC, delisma approved these changes
🚀 LGTM
p.s.If you could change the title of the PR to `Create 2024-06-05-unified-design-system posts`

2024-06-06 17:44 UTC, jmealing commented
@delisma I did change it already? is that the wrong place?
<img width="570" alt="Screenshot 2024-06-06 at 1 44 14 PM" src="https://github.com/canada-ca/blogue-canada-ca-blog/assets/31008799/6eea0429-f1e6-4778-b51b-f0ad75e86f2c">

2024-06-06 18:31 UTC, merged

2024-06-06 18:36 UTC, delisma commented
> @delisma I did change it already? is that the wrong place? <img alt="Screenshot 2024-06-06 at 1 44 14 PM" width="570" src="https://private-user-images.githubusercontent.com/31008799/337378399-6eea0429-f1e6-4778-b51b-f0ad75e86f2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTkyMTksIm5iZiI6MTcxNzY5ODkxOSwicGF0aCI6Ii8zMTAwODc5OS8zMzczNzgzOTktNmVlYTA0MjktZjFlNi00Nzc4LWI1MWItZjBhZDc1ZTg2ZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE4MzUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMDNmNmNmMzY5NGFkYjVmZDRmNGZmZmNjMjczMjg4YjdhYmY1NmZhMThiZGQyMjMzM2U2ZGI5MjZjMGIyZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vLHsLoIQ-ltVXDDqLJXdrZm3lT1T2prG3X5zKXGkcH0">

Yes! It misses the action Create and we should use yesterday's date

2024-06-06 18:38 UTC, delisma commented
Never mind I was able to change it